name: Build

on:
  push:
    branches:
      - main 
  pull_request:

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Compile
        run: mkdir -p build && cd build && cmake .. && make && cd ..
